# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03d56d45b0c8222ac53fa2d2f864b14df84cf7c5f2b9c0e69bcad33ccdea5f0502db1d805b36ab2516972f7200b3d6d70c6e4aeaf55511f79dc079ea4e1d5edc

test:
  secret_key_base: fb04e307e289ca2e8ccc8879db14a57dbc90dea4e461183e463dd2318e51856d4794064e7e3dccff4ca258b6a8cdb74d4ffeafccb82b615291409abeff36bc3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
